<a href="https://colab.research.google.com/github/nikesh623/AI_ML-Elevate_X/blob/main/Colab/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy (Numerical Python)
- python library used to working with arrays
- it also uses linear algebra, fourier transform, and matrices operations
- Why is it diff than list?
  - its because its speed, numpy arrays are stored at one contineous place in memory, so process can be very efficient and fast
  


In [ ]:
!pip install numpy

In [ ]:
import numpy as np
print(np.__version__)

2.1.3


### Creating an arrays using numpy

In [ ]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


Create a NumPy ndarray Objects

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
## 0-D Arrays
import numpy as np
arr = np.array(42)
print(arr)

42


In [ ]:
## 1-D array
arr = np.array([1,2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
## 2-D arrya
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
## 3-D array
arr = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Check Number of Dimensions in an Numpy Array?

In [ ]:
# Check Number of Dimensions in an Numpy Array?
import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
# Create an array of 5 dim and verify its dim

import numpy as np

arr = np.array([1,2,3,4], ndmin=64)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1
                                                                2
                                                                3
                                                                4]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
number of dimensions : 64


### Access Array Elements

In [ ]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr[2])

3


In [ ]:
# 3rd and 4th element add

import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


Accessing 2-D array

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [ ]:
print('second last element on 2nd row', arr[1, 3])

second last element on 2nd row 9


Assignment:

- You need to search and explore by yourself about numpy following features:
  - indexing
  - slicing
  - data type
  - array shape and reshape
  - sorting in numpy
  - array search
  - apply filters
  - random number genration
  - array join
  