<a href="https://colab.research.google.com/github/nikesh623/AI_ML-Elevate_X/blob/main/Colab/OOP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# OOP

##1. Introduction to NumPy

In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)

[10 20 30 40 50]


##2. Indexing

In [3]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[2])
print(arr[-1])

10
30
50


2D indexing

In [4]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr[0, 1])
print(arr[1, 2])

20
60


##3. Slicing

In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])

[20 30 40]


##4. Data Type (dtype)

In [6]:
import numpy as np

arr = np.array([10, 20, 30])

print(arr.dtype)

int64


In [ ]:
arr = np.array([1.5, 2.5, 3.5])

print(arr.dtype)

In [ ]:
arr = np.array([1, 2, 3], dtype=float)

print(arr)
print(arr.dtype)

##5. Array Shape

In [ ]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.shape)

##6. Reshape

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(2, 3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr.reshape(2, -1))

##7. Sorting in NumPy

In [ ]:
import numpy as np

arr = np.array([50, 10, 40, 20, 30])

sorted_arr = np.sort(arr)

print(sorted_arr)

##8. Array Search

In [8]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

result = np.where(arr > 25)

print(result)

(array([2, 3, 4]),)
